version: "3"

services:

    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: password
        networks:
            - learn-docker-network
    
    dotnet:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 5000:80
        networks:
            - learn-docker-network

networks:
    
    learn-docker-network:
        driver: bridge
